### PR TITLE
Fix tests for Python 3.7

### PR DESCRIPTION
**Pull request by brenmous**
Fixes tests for Python 3.7 and switches Travis CI to Python 3.7.

Change summary:
- Update to matplotlib 3.2.1
  - In penetration_depth1d plotting, `plt.loglog` complained about there being no positive values despite X and Y both being all positive (this was on matplotlib 3.1.2). Upgrading to matplotlib 3.2.1 fixed this.
- A previous change I had made to make `penetration.get_penetration_depth` get period by providing period in seconds rather than index broke penetration depth 3D. The 3D variant was using that function to get period by index and another function (`get_penetration_depth_generic`) to get period by value. I've refactored this and there are now functions `get_penetration_depth_by_period` and `get_penetration_depth_by_index`. I've reimplemented the ability to get period by index for 2D by supplying the `period_by_index` keyword argument to plot2Dprofile.
- Adding arguments to `make_z_mesh_new` broke a test. Because it's a class method, I removed these arguments and made it get the required parameters from the owner model instance in the body of the function. The exception is `n_layers`, which is optional and the value will be taken from the model object if not provided. `n_layers` is modified before being passed to the function when used in `model.add_topography_to_model2`.  
- The change from non-guaranteed ordering of dicts in Python 2 to ordering by order of insertion in Python 3 broke `data.write_data_file` tests. `EDICollection.get_periods_by_stats` iterated through the periods on the stations and placed them into a dict to process how often each period occurs, then ordered by occurrence. The dict items were then placed in a list and returned. In Python 2, the periods have an arbitrary ordering and in Python 3 they are ordered by period as well as occurrence, so the test fails due to a mismatch between the data files written with Python 2 and Python 3 due to the ordering of periods. The solution is to regenerate the ModEm.dat reference files.
- Various reference ModEm.rho files had to be regenerated due to the new log scaling of `make_z_mesh_new`. **While these looked sane to me, it would be a good idea if an expert could double check they're correct** - see commits [2f9afca](https://github.com/MTgeophysics/mtpy/commit/2f9afcaf9965615fd41092844e75c05e61712580) and [6f2b5d3](https://github.com/MTgeophysics/mtpy/commit/6f2b5d37f5dce1de42dff48e5925db4d8d394eaa).
- `PTShapefile` was expecting `project_point_ll2utm` to return UTM zone as a `SpatialReference`. I've changed it create the `SpatialReference` itself.

That's the major changes! There were some minor syntax fixes as well.

### CODE REVIEW

**Comment by brenmous** [comment]
That last merge commit was fixing a conflict in get_penetration_depth_by_index

**Comment by zhang01GA** [comment]
I will have a review 
(For some unknown reason, I have not been receiving any notifications from github recently)

**Comment by zhang01GA** [comment]
Checked out this branch and ran all unit-tests in my Ubuntu18.04 with ananconda Py3.7. 
Will try win10 and review code changes later. 

```
(mtpy3.7) fzhang@zubuntu1804 ~/Githubz/mtpy (bren-fixtests) 
 $ pytest -v --ignore=tests/SmartMT tests
```
========== 192 passed, 6 skipped, 3168 warnings in 1493.93s (0:24:53)  ========

**Comment by brenmous** [comment]
Thanks Fei, I actually forgot to test this on Windows so please let me know if there's issues

**Pull request merged**
